module.exports = [
  "Alcalá del Obispo",
  "Almudévar",
  "Banastas",
  "Casbas de Huesca",
  "Huesca",
  "Loarre",
  "Loscorrales",
  "Murillo de Gállego",
  "Siétamo",
  "Santa Eulalia de Gállego",
  "Vicién",
  "Aínsa-Sobrarbe",
  "La Fueva",
  "Gistaín",
  "Labuerda",
  "El Pueyo de Araguás",
  "San Juan de Plan",
  "Benasque",
  "Castejón de Sos",
  "Villanova",
  "Santa Cilia",
  "El Grado"
]
