module.exports = [
  "Alcalá d’o Bispe",
  "Almudébar",
  "Banastars",
  "Casbas de Uesca",
  "Uesca",
  "Lobarre",
  "Os Corrals",
  "Morillo de Galligo",
  "Sietemo",
  "Santolaria de Galligo",
  "Bizién",
  "L’Aínsa-Sobrarbe",
  "A Fueba",
  "Chistén",
  "A Buerda",
  "O Pueyo d’Araguás",
  "San Chuan de Plan",
  "Benás",
  "Castilló de Sos",
  "Billanoba",
  "Santa Zilia",
  "Lo Grau"
]
