module.exports = [
  "Arén",
  "Benabarre",
  "Estopiñán del Castillo",
  "Laspaúles",
  "Monesma y Cajigar",
  "Montanuy",
  "Puente de Montañana",
  "Tolva",
  "Viacamp y Litera",
  "Alcampell",
  "Altorricón",
  "Baldellou",
  "Castillonroy",
  "Tamarite de Litera",
  "Vencillón",
  "Mequinenza",
  "Torrente de Cinca",
  "Velilla de Cinca",
  "Zaidín",
  "Fabara",
  "Fayón",
  "Nonaspe",
  "Aguaviva",
  "Belmonte de San José",
  "La Cañada de Verich",
  "La Codoñera",
  "La Ginebrosa",
  "Torrevelilla",
  "Arens de Lledó",
  "Beceite",
  "Calaceite",
  "Cretas",
  "Fórnoles",
  "La Fresneda",
  "Fuentespalda",
  "Mazaleón",
  "Monroyo",
  "Peñarroya de Tastavins",
  "Ráfales",
  "Torre de Arcas",
  "Torre del Compte",
  "Valdeltormo",
  "Valderrobres",
  "Valjunquera"
]

