module.exports = [
  "Areny de Noguera",
  "Benavarri",
  "Estopanyá",
  "Laspaúls",
  "Monesma i Caixigar",
  "Montanui",
  "Pont de Montanyana",
  "Tolba",
  "Viacamp i Lliterà",
  "El Campell",
  "El Torricó",
  "Valdellou",
  "Castellonroi",
  "Tamarit de Llitera",
  "Vensilló",
  "Mequinensa",
  "Torrent de Cinca",
  "Villella de Cinca",
  "Saidí",
  "Favara",
  "Faió",
  "Nonasp",
  "Aiguaviva de Bergantes",
  "Bellmunt de Mesquí",
  "La Canyada de Beric",
  "La Codonyera",
  "La Ginebrosa",
  "Torre de Vilella",
  "Arenys de Lledó",
  "Beseit",
  "Calaceit",
  "Queretes",
  "Fórnols",
  "La Freixneda",
  "Fontdespatla",
  "Massalió",
  "Montroig",
  "Pena-roja de Tastavins",
  "Ráfels",
  "Torredarques",
  "La Torre del Comte",
  "La Vall del Tormo",
  "Vall de Roures",
  "Valljunquera"
]
